---
title: "ECO395M: Exercise 1"
author: "Steven Kim and Shreekara Shastry"
date: ""
output:
  md_document:
    variant: markdown_github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(rsample)
library(caret)
library(modelr)
library(knitr)
library(mosaic)
library(parallel)
library(foreach)
```

## 1) Data visualization
```{r, echo=FALSE}
data = read_csv('capmetro_UT.csv')

# Recode the categorical variables in sensible, rather than alphabetical, order
data = mutate(data,
               day_of_week = factor(day_of_week,
                 levels=c("Mon", "Tue", "Wed","Thu", "Fri", "Sat", "Sun")),
               month = factor(month,
                 levels=c("Sep", "Oct","Nov")))

data_1 = data %>% 
  group_by(hour_of_day, day_of_week, month) %>%
  summarize(avg_boarding = mean(boarding))

ggplot(data_1) +
  geom_line(aes(x=month, y=avg_boarding,color=month)) +
    labs(x = 'Month', y = 'Average Number of Boardings', color = 'Airport',
       title = 'Average Number of Boardings based on Day of the Week',
       caption = 'Avg number of boardings is broadly similar on weekdays 
                  and it dips over the weekend as expected for all three months
                  hour of peak boarding remains consitent between 3 and 5 pm
                  since its the common time for the classes to end') +
  facet_wrap(~day_of_week)

data_2 = data %>% 
  group_by(day_of_week, hour_of_day) %>%
  summarize(max_boarding = max(boarding))
```

```{r}
ggplot(data) +
  geom_point(aes(x=temperature, y=boarding, color = weekend=='weekend')) +
  scale_colour_manual(name = 'Weekend', values = setNames(c('blue','red'),c(T, F))) +
  facet_wrap(~hour_of_day) +
      labs(x = 'Temperature in F', y = 'Boardings', color = 'Weekend',
       title = 'Number of Boardings variation based on the Tempereature',
       caption = 'Number of boardings is smaller over the weekends 
       compared to the weekdays as expected across all all values 
       of temperature and the time of the day except from 6 to 9am,
       i.e before the college starts')
```
## 2) Saratoga house prices
```{r}
data(SaratogaHouses)

K_folds = 5

saratoga_folds = crossv_kfold(SaratogaHouses, k=K_folds)

#linear model

saratogalinear = map(saratoga_folds$train, ~ lm(price ~ . - pctCollege - sewer - newConstruction + rooms:bathrooms, data = .))
errs = map2_dbl(saratogalinear, saratoga_folds$test, modelr::rmse)

#knn model

#scale
saratoga_scaled = SaratogaHouses %>%
  mutate(across(c(lotSize, age, landValue, livingArea, pctCollege, bedrooms, fireplaces, bathrooms, rooms), scale))

saratoga_scaled_folds = crossv_kfold(saratoga_scaled, k=K_folds)

k_grid = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 
           30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200, 250, 300)

cv_grid = foreach(k = k_grid, .combine='rbind') %dopar% {
  models = map(saratoga_scaled_folds$train, ~ knnreg(price ~ . - pctCollege - sewer - newConstruction, k=k, data = ., use.all=FALSE))
  errs = map2_dbl(models, saratoga_scaled_folds$test, modelr::rmse)
  c(k=k, err = mean(errs), std_err = sd(errs)/sqrt(K_folds))
} %>% as.data.frame

ggplot(cv_grid) + 
  geom_point(aes(x=k, y=err)) + 
  geom_errorbar(aes(x=k, ymin = err-std_err, ymax = err+std_err)) + 
  scale_x_log10()

cv_grid_final = cv_grid %>% filter(err == min(cv_grid$err))
rownames(cv_grid_final) = c("KNN Model")
cv_grid_final = rbind(cv_grid_final, data.frame(k="NA", err = mean(errs), std_err = sd(errs)/sqrt(K_folds),  row.names = c("Linear Model"))) %>% dplyr::select(-std_err)
colnames(cv_grid_final) = c("k", "rMSE")
kable(cv_grid_final)
```

choose k = `r cv_grid_final[1,1]`, standard error is smaller for the linear model.


## 3) Classification and retrospective sampling
```{r}
data_g = read_csv('german_credit.csv')
prob_g = xtabs(~history+Default, data=data_g) %>%
  prop.table %>%
  round(3)

history = c("good","poor","terrible")
default_prob = c(5.3, 19.7, 5.0)
prob_table = as.data.frame(list(history=history, default_prob=default_prob))

ggplot(prob_table) +
  geom_col(aes(x=history, y=default_prob, fill=history)) +
    labs(x = 'History', y = 'Default % Probability', color = 'History')
```

```{r}

german_credit = initial_split(data_g, prob=0.8)
german_credit_train = training(german_credit)
german_credit_test = testing(german_credit)

german_credit_model = glm(Default ~ duration + amount + installment + age + history + purpose + foreign, data = german_credit_train, family = binomial)

coef(german_credit_model) %>% round(2)

phat_test_german_credit = predict(german_credit_model, german_credit_test, type='response')

yhat_test_german_credit = ifelse(phat_test_german_credit > 0.5, 1, 0)

confusion_out_logit = table(y= german_credit_test$Default, yhat = yhat_test_german_credit)

confusion_out_logit
```
## 4) Children and hotel reservations

```{r}
hotels_dev = read_csv("hotels_dev.csv")
hotels_val = read_csv("hotels_val.csv")

K_folds = 5

hotels_dev_folds = crossv_kfold(hotels_dev, k=K_folds)

k_grid = c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 
           30, 35, 40, 45, 50, 60, 70, 80, 90, 100, 125, 150, 175, 200, 250, 300)

hotels_baseline1 = map(hotels_dev_folds$train, ~ glm(children ~ market_segment + adults + customer_type + is_repeated_guest, data = ., family = 'binomial'))
hotels_baseline1_err = map2_dbl(hotels_baseline1, hotels_dev_folds$test, modelr::rmse) %>% mean

hotels_baseline2 = map(hotels_dev_folds$train, ~ glm(children ~ -arrival_date, data = .))
hotels_baseline2_err = map2_dbl(hotels_baseline2, hotels_dev_folds$test, modelr::rmse) %>% mean

hotels_lpm = map(hotels_dev_folds$train, ~ lm(children ~ market_segment + adults + customer_type + is_repeated_guest, data = .))
hotels_lpm_err = map2_dbl(hotels_lpm, hotels_dev_folds$test, modelr::rmse) %>% mean

hotels_errs = data.frame(c(hotels_baseline1_err, hotels_baseline2_err, hotels_lpm_err))
colnames(hotels_errs) = c("Out-of-Sample RMSE")
rownames(hotels_errs) = c("Baseline 1", "Baseline 2", "Linear (Logit) Model")
kable(hotels_errs)
```


